version: '3.9'

services:
  safenet-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: safenet-api
    ports:
      - "8000:8000"

  safenet-dashboard:
    build: ./dashboard
    container_name: safenet-dashboard # the main part
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://safenet-api:8000
 
